//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SachLapTrinh.Data_Access_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public string BookID { get; set; }
        public string BookName { get; set; }
        public string Tags { get; set; }
        public string Publisher { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public string Authors { get; set; }
        public Nullable<int> Pages { get; set; }
        public Nullable<double> Size { get; set; }
        public string BookDescription { get; set; }
    }
}
